---
engine: knitr
execute:
  eval: false
  warning: false
  message: false
metadata-files:
  - _authors.yml
  - _affiliations.yml
---

```{r}
#| results: asis
#| eval: true
#| echo: false
cat(make_figure("reproducible-journey"))
```

# Preface {.unnumbered}

## Welcome {.unnumbered}

Welcome to the world of reproduciblity and "The Repro Book - A Guide to Reproducible Research"!
The purpose of this book is to empower scientists, researchers, and students with the knowledge and skills needed to conduct a research project that is easy to reproduce.

## Who is this book for? {.unnumbered}

This guide is meant to be a gentle introduction to reproducibility for (aspiring) scientists who want to conduct research more reproducable.
Whether you are conducting experiments, writing code, collaborating with scientific peers, or managing complex data sets, this book conveys useful concepts with hands-on tips and exercises to enhance the reproducibility of your research project.
While this book was developed with scientists in mind, it is open to anyone who wants to learn more about reproducibility.
We try to avoid technical jargon as much as we can.
When we discuss best practices about reproducible guidelines, we try to offer multiple alternatives but also give opinionated recommendations as guidance to new users.

## What is the purpose of this book? {.unnumbered}

Reproducability can take your scientific projects to the next level.
By enhancing reproducibility, you will strengthen your results and evidence from your analysis [@community2022].
Of course, conducting research projects considering reproduciblity also adds some layer of complexity to your workflow.
We aim to simplify this workflow as much as possible for you. Whether you are new to version control or have dabbled in it before, this book aims to add something for all levels of expertise.


## How to use this book? {.unnumbered}

We believe in **learning by doing** and try to **focus on implementation** as much as possible.
The concepts introduced in this book are accompanied by practical examples and hands on exercises. <!--# and quizzes?-->
Feel free to follow the exercises to gain the necessary "muscle memory" to start enhancing the reproducibility of your work step-by-step.
Further, we recommend to work with a current research projects of yourself to apply different steps making your research more reproducible.
However, we also provide an example project, which you can download [here](https://osf.io/23mvn/). <!--# update link, when the project is finally published-->

This book was initially created for the full-semester course "[Open Science in Practice: A Toolkit for Research](https://osf.io/23mvn/)" at [University of Hamburg](https://www.uni-hamburg.de), Germany.
The book is therefore structured for a course that is spread out across multiple sessions.
Each chapter and the accompanying exercises should roughly fill 90 minutes of class time during a course.

This book is available in HTML format and will soon be available as PDF version.
However, we recommend using the **HTML version** for the most up-to-date content. The HTML version in continuously updated with new material, corrections, and interactive elements, ensuring you always have access to the latest information.
The PDF version will be a static snapshot and may become outdated over time, making it useful for offline reading and archival but less reliable for the most current information.

## How can I contribute? {.unnumbered}

This book is constantly evolving and meant as a living resource, and your input can make it even better!
If you spot typos, have suggestions for improvement, or want to contribute new content, we welcome your involvement!
If you find a typo, have an idea for a new chapter or want to see a specific topic covered you are more than welcome to [open an issue]({{< var links.issues >}}) or submit a pull request in the [GitHub repository]({{< var project.repo-url >}}) of this book. 