FROM lnnrtwttkhn/quarto-docker:latest

ENV RENV_CONFIG_AUTOLOADER_ENABLED FALSE
ENV RENV_AUTOLOAD_ENABLED FALSE

ENV RENV_VERSION v1.0.11
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"

COPY renv.lock renv.lock

RUN mkdir -p renv
COPY .Rprofile .Rprofile
COPY renv/activate.R renv/activate.R
COPY renv/settings.json renv/settings.json

RUN R -e "renv::restore()"
