name: Render and Deploy Quarto Site

on:
  push:
    branches:
      - main
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      IMAGE_NAME: lnnrtwttkhn/repro-book

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Quarto Docker image
        run: |
          docker pull $IMAGE_NAME:latest

      - name: Render Quarto website
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace $IMAGE_NAME:latest \
            quarto render /workspace

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
